"""Run every command the guides tell a person to run.

A guide can only be trusted if its commands work. This lifts them out of README.md and
docs/applets.md and runs them:

* read-only ones run as they are;
* the ones that change something (select, enable, disable, enable-source, disable-source) run with
  XDG_CONFIG_HOME pointing at a scratch directory that holds the shipped applets, so the real
  configuration is never touched;
* ones that would install, restart a service or copy a file are not run, but what they name is
  checked to exist: the make target, the service unit, the file.

A command fails this test only if it exits non-zero or reports that a command or file was not
found. An empty value is fine - this machine may have no broker, no mailbox endpoint and no
weather, and the guides say so.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = [os.path.join(REPO, "README.md"), os.path.join(REPO, "docs", "applets.md")]
SCRATCH = tempfile.mkdtemp(prefix="g13-guide-")
failures = []

CHANGES = ("--select", "--enable ", "--disable", "--enable-source", "--disable-source")
SKIP = ("make ", "systemctl", "cp ", "install ", "sudo", "apt", "git ", "pip ", "curl", "printf",
        "find ", "awk ", "for d in", "sleep", "cat ", "ls ", "g13-gui")
# examples a reader is meant to substitute into: nothing to run
PLACEHOLDER = re.compile(r"FILE|/path/to/|<[a-z-]+>|NAME|SPEC")


def commands():
    """Every command a guide shows: a `$ ...` line, or a line in a bash block naming a tool."""
    for path in DOCS:
        in_bash = False
        for number, line in enumerate(open(path, encoding="utf-8").read().splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("```"):
                in_bash = stripped.startswith("```bash")
                continue
            if stripped.startswith("$ "):
                yield path, number, stripped[2:]
            elif in_bash and re.match(r"^(g13-[a-z-]+|make)\b", stripped) and not stripped.startswith("#"):
                yield path, number, stripped


def make_target(name):
    makefile = os.path.join(REPO, "g13-driver", "src", "Makefile")
    return any(line.startswith(name + ":") for line in open(makefile).read().splitlines())


def unit_exists(name):
    for root in (os.path.join(REPO, "g13-visuals", "systemd"), os.path.join(REPO, "g13-driver", "src")):
        if os.path.isdir(root):
            for found in os.listdir(root):
                if found.startswith(name):
                    return True
    return False


# a scratch configuration holding the shipped applets, so `--select applet:gpu` resolves
os.makedirs(os.path.join(SCRATCH, "g13", "applets"), exist_ok=True)
for name in os.listdir(os.path.join(REPO, "g13-visuals", "applets")):
    shutil.copy2(os.path.join(REPO, "g13-visuals", "applets", name),
                 os.path.join(SCRATCH, "g13", "applets", name))

ran = checked = won = 0
for path, number, command in commands():
    where = "%s:%d" % (os.path.basename(path), number)
    if PLACEHOLDER.search(command):
        checked += 1
        continue
    if command.startswith(SKIP):
        parts = command.split()
        if parts[0] == "make" and len(parts) > 1 and not parts[1].startswith("-"):
            target, ok = parts[1], make_target(parts[1])
        elif parts[0] == "systemctl":
            unit = next((p for p in parts if p.startswith("g13")), "")
            target, ok = unit, unit_exists(unit.replace(".service", ""))
        elif parts[0] in ("cp", "install"):
            source = next((p for p in parts[1:] if "/" in p and not p.startswith("-")), "")
            target = source
            ok = bool(source) and os.path.exists(os.path.join(REPO, source.lstrip("./")))
        elif parts[0] == "g13-gui":
            # generated by the build (it is in .gitignore): what must exist is the target that makes it
            target, ok = "build-gui", make_target("build-gui")
        else:
            checked += 1
            continue
        checked += 1
        if not ok:
            failures.append("%s: %s names %r, which does not exist" % (where, command, target))
        continue

    environment = dict(os.environ)
    if any(flag in command for flag in CHANGES):
        environment["XDG_CONFIG_HOME"] = SCRATCH
    environment["G13_HOME"] = os.path.join(SCRATCH, "g13")
    try:
        finished = subprocess.run(["bash", "-c", command], capture_output=True, text=True,
                                  timeout=30, env=environment, cwd=REPO)
    except subprocess.TimeoutExpired:
        failures.append("%s: %s timed out after 30s" % (where, command))
        continue
    ran += 1
    output = (finished.stdout or "") + (finished.stderr or "")
    if finished.returncode != 0:
        last = (output.strip().splitlines() or [""])[-1]
        failures.append("%s: %s exited %d: %s" % (where, command, finished.returncode, last))
    elif re.search(r"command not found|No such file or directory", output):
        line = [item for item in output.splitlines() if "not found" in item or "No such" in item][:1]
        failures.append("%s: %s: %s" % (where, command, line))
    else:
        won += 1

print("commands run: %d   names checked without running: %d" % (ran, checked))
print("ran clean: %d" % won)
for problem in failures:
    print("FAIL", problem)
print("GUIDE RUNS TEST: all commands work" if not failures
      else "GUIDE RUNS TEST: %d problems" % len(failures))
shutil.rmtree(SCRATCH, ignore_errors=True)
sys.exit(0 if not failures else 1)
